# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-09-24 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swivapp', '0002_remove_swiv_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='swiv',
            name='Timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='swiv',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='swiv',
            name='content',
            field=models.CharField(max_length=140),
        ),
    ]
