# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-10-15 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swivapp', '0005_auto_20180928_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='swiv',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swivapp.Swiv'),
        ),
    ]
