# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-10-17 19:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swivapp', '0009_remove_swiv_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='swiv',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
