# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-10-17 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swivapp', '0010_swiv_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swiv',
            name='comment',
        ),
        migrations.AddField(
            model_name='swiv',
            name='comment',
            field=models.BooleanField(default=False, verbose_name='Is a comment'),
        ),
    ]
